import Link from "next/link";

type Guia = { resumen: string; pasos: string[]; siguiente: { href: string; texto: string }; terminos?: string };
const guias: Record<string, Guia> = {
  "/informes": { resumen: "Consulta y descarga ventas, evaluación del modelo y estados de pedidos del escenario.", pasos: ["Elige fechas y versión del modelo; pulsa Consultar para aplicar.", "Cambia entre Ventas, Pronósticos y Pedidos. Los detalles de productos se abren en un diálogo.", "Descarga el CSV del período completo, aunque estés viendo una sola página."], siguiente: { href: "/", texto: "Volver al dashboard" }, terminos: "Unidades: cantidades vendidas, sin ingresos calculados. Fecha del escenario: día histórico al que pertenece el dato. Estado del pedido: situación actual del mensaje, no recepción de stock." },
  "/": { resumen: "Empieza con los datos, revisa el plan y envía un pedido de prueba a tu Telegram.", pasos: ["Carga el historial, las recetas y el inventario inicial.", "Configura las ofertas del proveedor y verifica tu chat.", "Programa un plan y revisa sus faltantes en Compras."], siguiente: { href: "/inicializacion", texto: "Revisar datos iniciales" } },
  "/inicializacion": { resumen: "Prepara FoodSave con tus archivos. Primero se validan; después decides si guardarlos.", pasos: ["Elige dos Excel o cinco CSV y las fechas históricas del escenario.", "Revisa la vista previa y corrige los errores de archivo o fila.", "Confirma la carga y sigue la preparación del modelo sin volver a subir los archivos."], siguiente: { href: "/productos", texto: "Ver productos cargados" }, terminos: "Fecha del escenario: día histórico que quieres planificar. Referencia de stock: cierre previo que representa tu inventario inicial." },
  "/inicializacion/piloto": { resumen: "Carga rápida del CSV bakery: prepara ventas y modelo. Las recetas y el stock se completan en Datos iniciales.", pasos: ["Sube el CSV original de ventas del piloto.", "Sigue la preparación del modelo; si falla, reintenta sin cargar el CSV otra vez.", "Completa catálogo, recetas e inventario con la carga completa."], siguiente: { href: "/inicializacion", texto: "Abrir carga completa" } },
  "/productos": { resumen: "Este es tu catálogo. Los productos seleccionados para la demo participan en la planificación.", pasos: ["Revisa nombres y códigos importados.", "Filtra los productos de la demostración.", "Comprueba que cada producto que vas a planificar tenga receta y stock registrado."], siguiente: { href: "/recetas", texto: "Revisar recetas" }, terminos: "Código del archivo (SKU): identifica el producto en las ventas importadas. El catálogo no representa cantidades de inventario." },
  "/ventas": { resumen: "Consulta las unidades vendidas por producto y fecha. Una fecha sin registro significa dato desconocido.", pasos: ["Filtra por producto y fechas.", "Abre el historial de una venta para ver sus revisiones.", "Si eres administrador, corrige una cantidad e indica el motivo."], siguiente: { href: "/pronosticos", texto: "Ver pronósticos" }, terminos: "Una venta de cero debe estar registrada explícitamente. Las ventas históricas importadas no descuentan inventario." },
  "/ingredientes": { resumen: "Define los insumos de tus recetas y la unidad en que se mide cada uno.", pasos: ["Consulta los ingredientes activos.", "Registra el código, nombre y unidad base de un ingrediente nuevo.", "Usa esa misma unidad en recetas, stock y conversiones del proveedor."], siguiente: { href: "/recetas", texto: "Ver recetas" }, terminos: "Unidad base: medida común del ingrediente, por ejemplo g. Una bolsa de compra necesita declarar cuántos g contiene." },
  "/recetas": { resumen: "Indica cuánto ingrediente necesita una unidad de cada producto.", pasos: ["Selecciona el producto y revisa su receta vigente.", "Para cambiarla, registra una versión con ingredientes, cantidades y motivo.", "Los planes anteriores conservan la receta con la que se calcularon."], siguiente: { href: "/inventario", texto: "Revisar inventario" }, terminos: "Cantidad por unidad: ingrediente necesario para fabricar un solo producto. Versión: copia de la receta que permite explicar un plan anterior." },
  "/inventario": { resumen: "Consulta cuánto stock cuenta para una fecha del escenario y registra ajustes explícitos.", pasos: ["Elige la fecha histórica y el tipo de artículo.", "Abre los lotes para revisar vencimiento y cantidades excluidas.", "Para ajustar, elige un lote, suma o resta una cantidad e indica el motivo."], siguiente: { href: "/planificacion", texto: "Ver planes" }, terminos: "Lote: grupo de existencias con fechas propias. Disponible: stock que cuenta en la fecha seleccionada. Registrar un ajuste sí cambia el saldo." },
  "/proveedores": { resumen: "Prepara las ofertas de compra y conecta tu propio chat para recibir la demostración.", pasos: ["Configura el bot de Telegram y abre su chat con /start.", "Selecciona el proveedor, vincula tu chat y verifica el acceso.", "Registra una oferta preferida para cada ingrediente faltante. Después vuelve a Compras."], siguiente: { href: "/compras", texto: "Revisar y enviar pedidos" }, terminos: "Vincular guarda el destino; verificar comprueba que el bot puede acceder. Ninguna de esas dos acciones envía un pedido." },
  "/compras": { resumen: "Consulta los ingredientes faltantes, el modo de envío y la confirmación de tu Telegram.", pasos: ["Selecciona el plan y revisa los motivos si la propuesta está bloqueada.", "Tras verificar el chat en Proveedores, actualiza el estado del destino aquí.", "Revisa el texto, confirma tu chat y aprueba. La pantalla mostrará la confirmación de Telegram."], siguiente: { href: "/proveedores", texto: "Configurar proveedor y Telegram" }, terminos: "Propuesta: conjunto de pedidos del plan. Pedido: mensaje para un proveedor. Aprobado: envío autorizado. Enviado: Telegram confirmó el mensaje." },
  "/planificacion": { resumen: "Calcula producción sugerida e ingredientes faltantes a partir de un pronóstico guardado.", pasos: ["Selecciona un cálculo de pronóstico para crear el plan.", "Revisa producción, ingredientes disponibles y faltantes.", "Abre sus pedidos en Compras. Si cambió el stock o la receta, prepara un cálculo nuevo."], siguiente: { href: "/compras", texto: "Ver pedidos" }, terminos: "Producción sugerida = máximo entre cero y pronóstico menos stock. Faltante = necesidad de ingrediente menos stock disponible, con mínimo cero. Crear un plan no cambia stock." },
  "/pronosticos": { resumen: "Consulta cuántas unidades estima vender el modelo para cada fecha histórica.", pasos: ["Elige la versión del modelo.", "Abre un cálculo guardado para ver el pronóstico por producto.", "Consulta la evaluación para compararlo con las ventas reales o programa un plan."], siguiente: { href: "/automatizaciones", texto: "Programar un plan" }, terminos: "Modelo: versión entrenada con ventas anteriores. Cálculo de pronóstico: resultado guardado para una fecha. Sin cantidad significa que no pudo estimarse; no equivale a cero." },
  "/panel": { resumen: "Compara los pronósticos con ventas históricas conocidas para entender el error del modelo.", pasos: ["Selecciona la versión que quieres evaluar.", "Elige un día en el gráfico para ver sus productos.", "Revisa error y cobertura juntos: los datos desconocidos se excluyen de la comparación."], siguiente: { href: "/pronosticos", texto: "Ver cálculos del modelo" }, terminos: "MAE: error medio en unidades; menor es mejor. WAPE: error total relativo a ventas reales; menor es mejor. Cobertura: proporción de productos y fechas que sí se pudieron comparar." },
  "/automatizaciones": { resumen: "Elige cuándo ejecutar un plan y qué día histórico debe usar para sus cálculos.", pasos: ["Selecciona entre uno y cinco productos del catálogo.", "Indica una hora real próxima y la fecha histórica del escenario.", "Elige revisión manual o envío automático, guarda y sigue el resultado."], siguiente: { href: "/planificacion", texto: "Revisar planes generados" }, terminos: "Hora real: cuándo trabaja el sistema. Hora del escenario: contexto histórico del cálculo. La vista actualiza su estado automáticamente." },
  "/automatizaciones/ejecuciones": { resumen: "Sigue esta tarea: estado, intentos, resultado y motivo de cualquier fallo.", pasos: ["Espera mientras esté pendiente o en ejecución; el estado se actualiza solo.", "Consulta el resultado y sus enlaces al terminar.", "Si falla, revisa el mensaje del intento antes de crear otra solicitud."], siguiente: { href: "/automatizaciones", texto: "Volver a tareas programadas" }, terminos: "Intento: una ejecución de la misma tarea. Los reintentos de cálculos internos no autorizan repetir un mensaje de Telegram incierto." },
  "/configuracion": { resumen: "Administra el nombre del comercio, su zona horaria, moneda y modo de aprobación de pedidos nuevos.", pasos: ["Revisa los datos de esta instalación.", "Elige aprobación manual o envío automático como valor predeterminado.", "Guarda los cambios. Los pedidos existentes conservan su modo original."], siguiente: { href: "/proveedores", texto: "Configurar Telegram" } },
  "/usuarios": { resumen: "Administra quién puede entrar y qué acciones puede realizar.", pasos: ["Crea una cuenta con nombre, correo, contraseña inicial y rol.", "Edita el rol o desactiva una cuenta cuando corresponda.", "Debe permanecer al menos un administrador activo."], siguiente: { href: "/configuracion", texto: "Ver configuración" }, terminos: "Administrador: configura y modifica datos. Operador: consulta la información; las escrituras administrativas están restringidas." },
  "/notificaciones": { resumen: "El centro general de avisos es una función futura. Los envíos Telegram actuales se consultan en Compras.", pasos: ["Consulta errores e intentos en Automatizaciones.", "Consulta mensajes de pedido y su confirmación en Compras."], siguiente: { href: "/compras", texto: "Ver envíos Telegram disponibles" } },
};

export function GuiaPantalla({ ruta }: { ruta: string }) {
  const guia = guias[ruta.startsWith("/automatizaciones/ejecuciones/") ? "/automatizaciones/ejecuciones" : ruta];
  if (!guia) return null;
  return <section className="screen-guide" aria-label="Ayuda para esta pantalla">
    <div className="screen-guide-intro"><p>{guia.resumen}</p><Link href={guia.siguiente.href}>{guia.siguiente.texto} →</Link></div>
    <details><summary>Cómo usar esta pantalla y qué significan sus datos</summary><ol>{guia.pasos.map((paso) => <li key={paso}>{paso}</li>)}</ol>{guia.terminos && <p>{guia.terminos}</p>}</details>
  </section>;
}
